"""Render and persist reports from the report schema."""

from __future__ import annotations

import csv
import io
import re
from pathlib import Path

from qaagent.models import Evidence, Finding, MachineSummary, Report, SEVERITY_ORDER

# --- Secret redaction -------------------------------------------------------
#
# Evidence often captures cookies, auth headers, and tokens verbatim (that is
# the point of evidence) — but reports get shared: pasted into Test IO, attached
# to tickets, committed by accident. Redact credential material at render time
# so no output artifact carries a live secret.

_SECRET_PATTERNS = [
    # Flask/Django/JWT session cookies: "session=<long value>" — keep the name.
    (re.compile(r"(?i)\b(session|sess|sid|auth|token|jwt|csrftoken|remember)[-_=:\s]+([A-Za-z0-9._%+~-]{8,})"), r"\1=<redacted>"),
    # JWTs: header.payload.signature
    (re.compile(r"eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}"), "<jwt-redacted>"),
    # Bearer / API key schemes.
    (re.compile(r"(?i)\b(bearer|basic|nvapi|sk-)[\s-]*[A-Za-z0-9._-]{10,}"), r"\1<redacted>"),
    # Generic long hex/base64 blobs (64+ chars) — likely keys/hashes.
    (re.compile(r"\b[A-Fa-f0-9]{64,}\b"), "<hex-redacted>"),
]


def redact(text: str) -> str:
    """Mask credential-looking material in free text (evidence, descriptions)."""
    if not text:
        return text
    for pattern, replacement in _SECRET_PATTERNS:
        text = pattern.sub(replacement, text)
    return text


def _redact_finding(finding: Finding) -> Finding:
    """Copy a finding with credential material stripped from evidence/description."""
    data = finding.model_dump()
    data["description"] = redact(data.get("description") or "")
    if data.get("remediation"):
        data["remediation"] = redact(data["remediation"])
    for ev in data.get("evidence", []):
        if ev.get("detail"):
            ev["detail"] = redact(ev["detail"])
    return Finding.model_validate(data)


def _redacted_report(report: Report) -> Report:
    """Return a copy of the report safe to render into any output artifact."""
    return report.model_copy(
        update={"findings": [_redact_finding(f) for f in report.findings]}
    )


def _stamp(report: Report) -> str:
    return report.started_at.strftime("%Y%m%d-%H%M%S")


def render_markdown(report: Report) -> str:
    """Render a full report as Markdown, findings ranked by severity."""
    lines: list[str] = []
    lines.append(f"# Sentinel report — {report.target}")
    lines.append("")
    lines.append(f"- status: **{report.status}**")
    lines.append(f"- started: {report.started_at.isoformat()}")
    if report.finished_at:
        lines.append(f"- finished: {report.finished_at.isoformat()}")
        secs = int((report.finished_at - report.started_at).total_seconds())
        lines.append(f"- elapsed: {secs}s")
    if report.summary:
        counts = " · ".join(
            f"{sev.value} {report.summary.by_severity.get(sev.value, 0)}"
            for sev in SEVERITY_ORDER
        )
        lines.append(f"- findings: {report.summary.total} ({counts})")
    lines.append("")
    lines.append("## Findings")
    lines.append("")

    if not report.findings:
        lines.append("_No findings._")
    else:
        ordered = sorted(
            report.findings,
            key=lambda f: (SEVERITY_ORDER.index(f.severity), f.detected_at),
        )
        for finding in ordered:
            lines.append(f"### {finding.severity.value} — {finding.title}")
            lines.append("")
            lines.append(f"- id: `{finding.id}`")
            lines.append(f"- category: {finding.category.value}")
            lines.append(f"- detected: {finding.detected_at.isoformat()}")
            if finding.url:
                lines.append(f"- url: {finding.url}")
            if finding.content_type:
                lines.append(f"- content-type: `{finding.content_type}`")
            if finding.description:
                lines.append("")
                lines.append(finding.description)
            if finding.remediation:
                lines.append("")
                lines.append(f"**Remediation:** {finding.remediation}")
            if finding.evidence:
                lines.append("")
                lines.append("Evidence:")
                for ev in finding.evidence:
                    detail = ev.detail or ev.url or ev.file or ""
                    lines.append(f"- `{ev.kind}` — {detail}")
            lines.append("")
    lines.append("---")
    lines.append("_Generated by Sentinel. Authorized testing only._")
    return "\n".join(lines)


def save_report(report: Report, output_dir: str | Path) -> Path:
    """Write the report to output_dir as Markdown and return its path."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{_stamp(report)}.md"
    path.write_text(render_markdown(_redacted_report(report)), encoding="utf-8")
    return path


def save_report_json(report: Report, output_dir: str | Path) -> Path:
    """Write the full report as JSON (Pydantic schema) and return its path."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{_stamp(report)}.json"
    path.write_text(_redacted_report(report).model_dump_json(indent=2), encoding="utf-8")
    return path


_SEV_STYLE = {
    # severity -> (label color, tinted bg, border, dot)
    "critical": ("#f28286", "rgba(229,72,77,0.12)", "rgba(229,72,77,0.34)", "#e5484d"),
    "high": ("#f79457", "rgba(247,107,21,0.12)", "rgba(247,107,21,0.34)", "#f76b15"),
    "medium": ("#f0b95c", "rgba(245,166,35,0.12)", "rgba(245,166,35,0.32)", "#f5a623"),
    "low": ("#8fb0cf", "rgba(108,143,179,0.12)", "rgba(108,143,179,0.32)", "#6c8fb3"),
    "info": ("#98a1ab", "rgba(125,135,148,0.1)", "rgba(125,135,148,0.28)", "#7d8794"),
}


def render_html(report: Report) -> str:
    """Render a full report as a self-contained HTML page (console design)."""
    counts = {}
    for f in report.findings:
        counts[f.severity.value] = counts.get(f.severity.value, 0) + 1
    total = len(report.findings)

    def badge(sev: str, n: int) -> str:
        fg, bg, bd, dot = _SEV_STYLE.get(
            sev, ("#98a1ab", "rgba(125,135,148,0.1)", "rgba(125,135,148,0.28)", "#7d8794")
        )
        return (
            f"<span class='sev' style='background:{bg};border-color:{bd}'>"
            f"<span class='dot' style='background:{dot}'></span>"
            f"<span style='color:{fg}'>{sev.upper()}</span>"
            f"<span class='n'>{n}</span></span>"
        )

    summary_line = " ".join(
        badge(s, counts.get(s, 0)) for s in ["critical", "high", "medium", "low", "info"]
    )
    # Proportional severity stack.
    segments = ""
    for sev in ["critical", "high", "medium", "low", "info"]:
        n = counts.get(sev, 0)
        if total and n:
            dot = _SEV_STYLE.get(sev, ("#98a1ab", "", "", "#7d8794"))[3]
            segments += f"<span style='width:{100 * n / total:.1f}%;background:{dot}'></span>"
    stack = f"<div class='stack'>{segments}</div>" if segments else ""

    findings_html = ""
    ordered = sorted(
        report.findings,
        key=lambda f: (SEVERITY_ORDER.index(f.severity), f.detected_at),
    )
    for finding in ordered:
        fg, bg, bd, dot = _SEV_STYLE.get(
            finding.severity.value,
            ("#98a1ab", "rgba(125,135,148,0.1)", "rgba(125,135,148,0.28)", "#7d8794"),
        )
        evidence_items = ""
        for ev in finding.evidence:
            detail = ev.detail or ev.url or ev.file or ""
            evidence_items += f"<li><code>{_esc(ev.kind)}</code> {_esc(detail)}</li>"
        evidence_block = (
            f"<div class='evlabel'>Evidence</div><ul class='evidence'>{evidence_items}</ul>"
            if evidence_items
            else ""
        )
        ct_line = (
            f"<div class='mime'>Content-Type: {_esc(finding.content_type)}</div>"
            if finding.content_type
            else ""
        )
        url_line = f"<div class='url'>{_esc(finding.url)}</div>" if finding.url else ""
        rem_line = (
            "<div class='remediation'><span class='rlabel'>Remediation</span>"
            f"{_esc(finding.remediation)}</div>"
            if finding.remediation
            else ""
        )
        findings_html += f"""
        <article class='finding' id='{_esc(finding.id)}' style='--edge:{dot}'>
          <div class='finding-header'>
            <span class='sev' style='background:{bg};border-color:{bd}'>
              <span class='dot' style='background:{dot}'></span>
              <span style='color:{fg}'>{finding.severity.value.upper()}</span>
            </span>
            <span class='finding-title'>{_esc(finding.title)}</span>
          </div>
          <div class='fid'>{_esc(finding.id)} &middot; {finding.category.value} &middot; detected {_esc(finding.detected_at.isoformat(timespec='seconds'))}</div>
          {url_line}
          {ct_line}
          <div class='description'>{_esc(finding.description)}</div>
          {rem_line}
          {evidence_block}
        </article>
        """
    status_color = "#66c07a" if report.status == "completed" else "#f28286"
    elapsed = ""
    if report.started_at and report.finished_at:
        secs = int((report.finished_at - report.started_at).total_seconds())
        elapsed = f"<span class='elapsed'>{secs}s</span>"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sentinel Report — {_esc(report.target)}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  :focus-visible {{ outline:2px solid #4c8dff; outline-offset:1px; }}
  body {{ font-family:"Inter","Segoe UI",system-ui,sans-serif; background:#0b0d10; color:#e8ebee;
         line-height:1.5; padding:28px 20px 60px; -webkit-font-smoothing:antialiased; }}
  .container {{ max-width:860px; margin:0 auto; }}
  .eyebrow {{ font-family:"JetBrains Mono",ui-monospace,monospace; font-size:9px; font-weight:600;
             letter-spacing:.17em; text-transform:uppercase; color:#6b747e; }}
  h1 {{ font-size:21px; font-weight:600; letter-spacing:-.015em; margin:6px 0 0; }}
  .meta {{ display:flex; flex-wrap:wrap; gap:8px 18px; align-items:baseline; margin:10px 0 16px;
          font-size:12px; color:#98a1ab; }}
  .meta .target {{ font-family:"JetBrains Mono",ui-monospace,monospace; font-size:11.5px; color:#7fa9f0; }}
  .status {{ font-family:"JetBrains Mono",ui-monospace,monospace; font-size:10px; font-weight:600;
            letter-spacing:.12em; }}
  .elapsed {{ font-family:"JetBrains Mono",ui-monospace,monospace; font-size:11px; color:#6b747e; }}
  .stack {{ display:flex; height:6px; border-radius:99px; overflow:hidden; background:#1a1e23; margin:2px 0 14px; }}
  .sev {{ display:inline-flex; align-items:center; gap:6px; font-family:"JetBrains Mono",ui-monospace,monospace;
         font-size:9.5px; font-weight:600; letter-spacing:.1em; padding:3px 8px; border-radius:4px;
         border:1px solid; white-space:nowrap; }}
  .sev .dot {{ width:5px; height:5px; border-radius:2px; flex:0 0 auto; }}
  .sev .n {{ opacity:.85; }}
  .summary {{ display:flex; gap:8px; flex-wrap:wrap; margin-bottom:20px; }}
  h2 {{ font-size:11px; font-weight:600; letter-spacing:.12em; text-transform:uppercase; color:#6b747e;
       margin:0 0 10px; }}
  .finding {{ position:relative; background:#121417; border:1px solid #22262c; border-radius:6px;
             padding:16px 18px 16px 20px; margin-bottom:10px; overflow:hidden; }}
  .finding::before {{ content:""; position:absolute; left:0; top:14px; bottom:14px; width:3px;
                     border-radius:2px; background:var(--edge,#22262c); }}
  .finding-header {{ display:flex; align-items:center; gap:10px; flex-wrap:wrap; }}
  .finding-title {{ font-size:14px; font-weight:600; letter-spacing:-.01em; }}
  .fid {{ font-family:"JetBrains Mono",ui-monospace,monospace; font-size:9px; color:#4d555e; margin-top:6px; }}
  .url {{ color:#7fa9f0; font-family:"JetBrains Mono",ui-monospace,monospace; font-size:11px;
         word-break:break-all; margin-top:6px; }}
  .mime {{ color:#98a1ab; font-size:10px; font-family:"JetBrains Mono",ui-monospace,monospace; margin-top:2px; }}
  .description {{ color:#c3c9d0; font-size:12.5px; margin-top:8px; }}
  .remediation {{ color:#c3c9d0; font-size:12px; margin-top:8px; }}
  .rlabel, .evlabel {{ display:block; font-size:9px; font-weight:600; letter-spacing:.12em;
                      text-transform:uppercase; color:#6b747e; margin-bottom:3px; }}
  .evlabel {{ margin-top:10px; }}
  .remediation .rlabel {{ color:#66c07a; }}
  .evidence {{ color:#98a1ab; font-size:11px; padding-left:16px; }}
  .evidence li {{ margin-top:3px; }}
  .evidence code {{ font-family:"JetBrains Mono",ui-monospace,monospace; background:#1a1e23;
                  border:1px solid #22262c; padding:1px 5px; border-radius:3px; font-size:10px; }}
  .empty {{ color:#4d555e; padding:28px; text-align:center; font-size:12.5px;
           border:1px dashed #22262c; border-radius:6px; }}
  footer {{ margin-top:26px; padding-top:12px; border-top:1px solid #22262c;
           font-family:"JetBrains Mono",ui-monospace,monospace; font-size:9px; color:#4d555e; }}
</style>
</head>
<body>
<div class='container'>
  <div class='eyebrow'>Sentinel security report</div>
  <h1>{_esc(report.target)}</h1>
  <div class='meta'>
    <span class='target'>{_esc(report.target)}</span>
    <span class='status' style='color:{status_color}'>● {_esc(report.status.upper())}</span>
    {elapsed}
    <span>{total} finding{'s' if total != 1 else ''}</span>
  </div>
  {stack}
  <div class='summary'>{summary_line}</div>
  <h2>Findings</h2>
  {findings_html if findings_html else '<div class="empty">No findings recorded.</div>'}
  <footer>Generated by Sentinel · authorized testing only · {_esc(report.started_at.isoformat(timespec='seconds'))}</footer>
</div>
</body>
</html>"""


def _esc(text: str) -> str:
    """Minimal HTML escaping for report content."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
    )


def save_report_html(report: Report, output_dir: str | Path) -> Path:
    """Write the report as a styled HTML file and return its path."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{_stamp(report)}.html"
    path.write_text(render_html(_redacted_report(report)), encoding="utf-8")
    return path


def save_report_csv(report: Report, output_dir: str | Path) -> Path:
    """Write the report as a CSV file and return its path."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{_stamp(report)}.csv"
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "id", "severity", "category", "title", "url",
        "content_type", "description", "remediation", "detected_at",
    ])
    ordered = sorted(
        _redacted_report(report).findings,
        key=lambda f: (SEVERITY_ORDER.index(f.severity), f.detected_at),
    )
    for f in ordered:
        writer.writerow([
            f.id,
            f.severity.value,
            f.category.value,
            f.title,
            f.url or "",
            f.content_type or "",
            f.description,
            f.remediation or "",
            f.detected_at.isoformat(),
        ])
    path.write_text(buf.getvalue(), encoding="utf-8")
    return path


# --- Test IO-style bug reports -------------------------------------------

# Test IO functional-bug severities are Low / High / Critical only. Map our
# five-level scale onto theirs the way their team leaders judge bugs.
_TESTIO_SEVERITY = {
    "critical": "Critical",
    "high": "High",
    "medium": "Low",
    "low": "Low",
    "info": "Low",
}


def render_testio_bug(report: Report, finding) -> str:
    """Render one finding as a Test IO-style bug report.

    Field order and phrasing follow Test IO's Bug Report Requirements:
    Feature / Severity / Title / URL / Steps to reproduce / Actual result /
    Expected result / Attachment / Used environment.
    """
    ev_http = [e for e in finding.evidence if e.kind == "http_response"]
    ev_other = [e for e in finding.evidence if e.kind != "http_response"]

    # Steps to reproduce: step 1 opens the target (their rule), then the
    # finding's URL + probe actions from the evidence chain.
    steps = [f"Open {report.target}"]
    if finding.url and finding.url != report.target:
        steps.append(f"Navigate to {finding.url}")
    for e in ev_http:
        if e.detail:
            steps.append(f"Send the request: {e.detail}")
    if len(steps) == 1:
        steps.append("Open the affected URL")

    # Actual result: the finding description plus concrete observed responses.
    actual_lines = [finding.description] if finding.description else []
    for e in ev_http:
        if e.detail:
            actual_lines.append(f"Observed response: {e.detail}")
    if finding.content_type:
        actual_lines.append(f"Response Content-Type: {finding.content_type}")
    actual = " ".join(actual_lines) if actual_lines else finding.title

    # Expected result: derived from the finding's remediation (the secure
    # behavior), phrased as what the app should do rather than what it fails
    # to do — their rule that actual/expected must not be mirror images.
    expected = finding.remediation or (
        "The application should handle this request securely and "
        "return the expected response without exposing unintended behavior."
    )

    lines = [
        "# Bug report (Test IO format)",
        "",
        f"- **Feature:** Security / Stability",
        f"- **Severity:** {_TESTIO_SEVERITY.get(finding.severity.value, 'Low')}",
        f"- **Title:** {finding.title}",
        f"- **URL:** {finding.url or report.target}",
        "",
        "## Steps to reproduce",
    ]
    for i, step in enumerate(steps, 1):
        lines.append(f"{i}. {step}")
    lines += [
        "",
        "## Actual result",
        actual,
        "",
        "## Expected result",
        expected,
        "",
        "## Attachment",
    ]
    if ev_other or ev_http:
        lines.append("Attach the evidence captured by Sentinel:")
        for e in ev_other + ev_http:
            detail = e.detail or e.url or e.file or ""
            lines.append(f"- [{e.kind}] {detail}")
    else:
        lines.append("_No attachment captured — add a screenshot of the observed behavior._")
    lines += [
        "",
        "## Used environment",
        "- Device/Browser: Chromium (Playwright headless)",
        f"- Tested URL: {report.target}",
        f"- Detected: {finding.detected_at.strftime('%Y-%m-%d %H:%M UTC')}",
    ]
    return "\n".join(lines)


def save_report_testio(report: Report, output_dir: str | Path) -> Path:
    """Write Test IO-style bug reports — one Markdown file per finding —
    plus a combined index. Returns the directory containing them."""
    out = Path(output_dir)
    bug_dir = out / f"testio-{_stamp(report)}"
    bug_dir.mkdir(parents=True, exist_ok=True)
    ordered = sorted(
        _redacted_report(report).findings,
        key=lambda f: (SEVERITY_ORDER.index(f.severity), f.detected_at),
    )
    index = [
        f"# Test IO bug reports — {report.target}",
        "",
        f"{len(ordered)} bug report(s), ready to paste into the Test IO form.",
        "",
    ]
    for i, f in enumerate(ordered, 1):
        slug = f.title.lower().replace(" ", "-")
        slug = "".join(c for c in slug if c.isalnum() or c == "-")[:60] or f"bug-{i}"
        path = bug_dir / f"{i:02d}-{f.severity.value}-{slug}.md"
        path.write_text(render_testio_bug(report, f), encoding="utf-8")
        sev = _TESTIO_SEVERITY.get(f.severity.value, "Low")
        index.append(f"{i}. [{sev}] **{f.title}** — `{path.name}`")
    (bug_dir / "00-INDEX.md").write_text("\n".join(index), encoding="utf-8")
    return bug_dir


def save_summary(
    report: Report,
    output_dir: str | Path,
    markdown_path: Path | str,
    json_path: Path | str,
) -> Path:
    """Write the stable machine-readable summary to latest.json (overwrites)."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    summary = MachineSummary.from_report(
        _redacted_report(report),
        report_markdown=str(markdown_path),
        report_json=str(json_path),
    )
    path = out / "latest.json"
    path.write_text(summary.model_dump_json(indent=2), encoding="utf-8")
    return path
